// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)
