version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    stdin_open: true
    environment:
      - REACT_APP_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/app"
      - "/go/pkg/mod/cache"
    environment:
      - STRIPE_SECRET_KEY
      - DB_URI=postgres://lilshopuser:lilshoppass@postgres/lilshopdb?sslmode=disable
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lilshopuser
      - POSTGRES_PASSWORD=lilshoppass
      - POSTGRES_DB=lilshopdb
  proxy:
    image: nginx:1.19-alpine
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 3000:80
    depends_on:
      - frontend
      - backend
volumes:
  dbdata:
