// Code generated by entc, DO NOT EDIT.

package order

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the order type in the database.
	Label = "order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPaymentIntentID holds the string denoting the payment_intent_id field in the database.
	FieldPaymentIntentID = "payment_intent_id"

	// EdgeOrderLineItems holds the string denoting the order_line_items edge name in mutations.
	EdgeOrderLineItems = "order_line_items"

	// Table holds the table name of the order in the database.
	Table = "orders"
	// OrderLineItemsTable is the table the holds the order_line_items relation/edge.
	OrderLineItemsTable = "order_line_items"
	// OrderLineItemsInverseTable is the table name for the OrderLineItem entity.
	// It exists in this package in order to avoid circular dependency with the "orderlineitem" package.
	OrderLineItemsInverseTable = "order_line_items"
	// OrderLineItemsColumn is the table column denoting the order_line_items relation/edge.
	OrderLineItemsColumn = "order_order_line_items"
)

// Columns holds all SQL columns for order fields.
var Columns = []string{
	FieldID,
	FieldPaymentIntentID,
}

var (
	// DefaultID holds the default value on creation for the id field.
	DefaultID func() uuid.UUID
)
