// Code generated by entc, DO NOT EDIT.

package cart

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the cart type in the database.
	Label = "cart"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeLineItems holds the string denoting the line_items edge name in mutations.
	EdgeLineItems = "line_items"

	// Table holds the table name of the cart in the database.
	Table = "carts"
	// LineItemsTable is the table the holds the line_items relation/edge.
	LineItemsTable = "line_items"
	// LineItemsInverseTable is the table name for the LineItem entity.
	// It exists in this package in order to avoid circular dependency with the "lineitem" package.
	LineItemsInverseTable = "line_items"
	// LineItemsColumn is the table column denoting the line_items relation/edge.
	LineItemsColumn = "cart_line_items"
)

// Columns holds all SQL columns for cart fields.
var Columns = []string{
	FieldID,
}

var (
	// DefaultID holds the default value on creation for the id field.
	DefaultID func() uuid.UUID
)
