// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/awolk/lil-shop/backend/ent/lineitem"
	"github.com/awolk/lil-shop/backend/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// LineItemDelete is the builder for deleting a LineItem entity.
type LineItemDelete struct {
	config
	hooks      []Hook
	mutation   *LineItemMutation
	predicates []predicate.LineItem
}

// Where adds a new predicate to the delete builder.
func (lid *LineItemDelete) Where(ps ...predicate.LineItem) *LineItemDelete {
	lid.predicates = append(lid.predicates, ps...)
	return lid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lid *LineItemDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lid.hooks) == 0 {
		affected, err = lid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LineItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lid.mutation = mutation
			affected, err = lid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lid.hooks) - 1; i >= 0; i-- {
			mut = lid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lid *LineItemDelete) ExecX(ctx context.Context) int {
	n, err := lid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lid *LineItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: lineitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: lineitem.FieldID,
			},
		},
	}
	if ps := lid.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, lid.driver, _spec)
}

// LineItemDeleteOne is the builder for deleting a single LineItem entity.
type LineItemDeleteOne struct {
	lid *LineItemDelete
}

// Exec executes the deletion query.
func (lido *LineItemDeleteOne) Exec(ctx context.Context) error {
	n, err := lido.lid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lineitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lido *LineItemDeleteOne) ExecX(ctx context.Context) {
	lido.lid.ExecX(ctx)
}
