// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/awolk/lil-shop/backend/ent/cart"
	"github.com/awolk/lil-shop/backend/ent/item"
	"github.com/awolk/lil-shop/backend/ent/lineitem"
	"github.com/awolk/lil-shop/backend/ent/order"
	"github.com/awolk/lil-shop/backend/ent/orderlineitem"
	"github.com/awolk/lil-shop/backend/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	cartFields := schema.Cart{}.Fields()
	_ = cartFields
	// cartDescID is the schema descriptor for id field.
	cartDescID := cartFields[0].Descriptor()
	// cart.DefaultID holds the default value on creation for the id field.
	cart.DefaultID = cartDescID.Default.(func() uuid.UUID)
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescCostCents is the schema descriptor for cost_cents field.
	itemDescCostCents := itemFields[2].Descriptor()
	// item.CostCentsValidator is a validator for the "cost_cents" field. It is called by the builders before save.
	item.CostCentsValidator = itemDescCostCents.Validators[0].(func(int) error)
	// itemDescID is the schema descriptor for id field.
	itemDescID := itemFields[0].Descriptor()
	// item.DefaultID holds the default value on creation for the id field.
	item.DefaultID = itemDescID.Default.(func() uuid.UUID)
	lineitemFields := schema.LineItem{}.Fields()
	_ = lineitemFields
	// lineitemDescQuantity is the schema descriptor for quantity field.
	lineitemDescQuantity := lineitemFields[1].Descriptor()
	// lineitem.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	lineitem.QuantityValidator = lineitemDescQuantity.Validators[0].(func(int) error)
	// lineitemDescID is the schema descriptor for id field.
	lineitemDescID := lineitemFields[0].Descriptor()
	// lineitem.DefaultID holds the default value on creation for the id field.
	lineitem.DefaultID = lineitemDescID.Default.(func() uuid.UUID)
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCompleted is the schema descriptor for completed field.
	orderDescCompleted := orderFields[2].Descriptor()
	// order.DefaultCompleted holds the default value on creation for the completed field.
	order.DefaultCompleted = orderDescCompleted.Default.(bool)
	// orderDescID is the schema descriptor for id field.
	orderDescID := orderFields[0].Descriptor()
	// order.DefaultID holds the default value on creation for the id field.
	order.DefaultID = orderDescID.Default.(func() uuid.UUID)
	orderlineitemFields := schema.OrderLineItem{}.Fields()
	_ = orderlineitemFields
	// orderlineitemDescQuantity is the schema descriptor for quantity field.
	orderlineitemDescQuantity := orderlineitemFields[1].Descriptor()
	// orderlineitem.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	orderlineitem.QuantityValidator = orderlineitemDescQuantity.Validators[0].(func(int) error)
	// orderlineitemDescUnitCostCents is the schema descriptor for unit_cost_cents field.
	orderlineitemDescUnitCostCents := orderlineitemFields[2].Descriptor()
	// orderlineitem.UnitCostCentsValidator is a validator for the "unit_cost_cents" field. It is called by the builders before save.
	orderlineitem.UnitCostCentsValidator = orderlineitemDescUnitCostCents.Validators[0].(func(int) error)
	// orderlineitemDescID is the schema descriptor for id field.
	orderlineitemDescID := orderlineitemFields[0].Descriptor()
	// orderlineitem.DefaultID holds the default value on creation for the id field.
	orderlineitem.DefaultID = orderlineitemDescID.Default.(func() uuid.UUID)
}
