// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/awolk/lil-shop/backend/ent/item"
	"github.com/awolk/lil-shop/backend/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescCostCents is the schema descriptor for cost_cents field.
	itemDescCostCents := itemFields[2].Descriptor()
	// item.CostCentsValidator is a validator for the "cost_cents" field. It is called by the builders before save.
	item.CostCentsValidator = itemDescCostCents.Validators[0].(func(int) error)
	// itemDescID is the schema descriptor for id field.
	itemDescID := itemFields[0].Descriptor()
	// item.DefaultID holds the default value on creation for the id field.
	item.DefaultID = itemDescID.Default.(func() uuid.UUID)
}
