// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	ID        string      `json:"id"`
	LineItems []*LineItem `json:"lineItems"`
}

type CheckOutReply struct {
	ClientSecret   string `json:"clientSecret"`
	TotalCostCents int    `json:"totalCostCents"`
}

type Item struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CostCents int    `json:"costCents"`
}

type LineItem struct {
	ID       string `json:"id"`
	Item     *Item  `json:"item"`
	Quantity int    `json:"quantity"`
}
