// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// CartsColumns holds the columns for the "carts" table.
	CartsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
	}
	// CartsTable holds the schema information for the "carts" table.
	CartsTable = &schema.Table{
		Name:        "carts",
		Columns:     CartsColumns,
		PrimaryKey:  []*schema.Column{CartsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "cost_cents", Type: field.TypeInt},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:        "items",
		Columns:     ItemsColumns,
		PrimaryKey:  []*schema.Column{ItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// LineItemsColumns holds the columns for the "line_items" table.
	LineItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "cart_line_items", Type: field.TypeUUID, Nullable: true},
		{Name: "line_item_item", Type: field.TypeUUID, Nullable: true},
	}
	// LineItemsTable holds the schema information for the "line_items" table.
	LineItemsTable = &schema.Table{
		Name:       "line_items",
		Columns:    LineItemsColumns,
		PrimaryKey: []*schema.Column{LineItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "line_items_carts_line_items",
				Columns: []*schema.Column{LineItemsColumns[2]},

				RefColumns: []*schema.Column{CartsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "line_items_items_item",
				Columns: []*schema.Column{LineItemsColumns[3]},

				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "payment_intent_id", Type: field.TypeString},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:        "orders",
		Columns:     OrdersColumns,
		PrimaryKey:  []*schema.Column{OrdersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// OrderLineItemsColumns holds the columns for the "order_line_items" table.
	OrderLineItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "unit_cost_cents", Type: field.TypeInt},
		{Name: "completed", Type: field.TypeBool},
		{Name: "order_order_line_items", Type: field.TypeUUID, Nullable: true},
		{Name: "order_line_item_item", Type: field.TypeUUID, Nullable: true},
		{Name: "order_line_item_original_line_item", Type: field.TypeUUID, Nullable: true},
	}
	// OrderLineItemsTable holds the schema information for the "order_line_items" table.
	OrderLineItemsTable = &schema.Table{
		Name:       "order_line_items",
		Columns:    OrderLineItemsColumns,
		PrimaryKey: []*schema.Column{OrderLineItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "order_line_items_orders_order_line_items",
				Columns: []*schema.Column{OrderLineItemsColumns[4]},

				RefColumns: []*schema.Column{OrdersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "order_line_items_items_item",
				Columns: []*schema.Column{OrderLineItemsColumns[5]},

				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "order_line_items_line_items_original_line_item",
				Columns: []*schema.Column{OrderLineItemsColumns[6]},

				RefColumns: []*schema.Column{LineItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CartsTable,
		ItemsTable,
		LineItemsTable,
		OrdersTable,
		OrderLineItemsTable,
	}
)

func init() {
	LineItemsTable.ForeignKeys[0].RefTable = CartsTable
	LineItemsTable.ForeignKeys[1].RefTable = ItemsTable
	OrderLineItemsTable.ForeignKeys[0].RefTable = OrdersTable
	OrderLineItemsTable.ForeignKeys[1].RefTable = ItemsTable
	OrderLineItemsTable.ForeignKeys[2].RefTable = LineItemsTable
}
