// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// CartsColumns holds the columns for the "carts" table.
	CartsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "payment_intent_id", Type: field.TypeString, Nullable: true},
	}
	// CartsTable holds the schema information for the "carts" table.
	CartsTable = &schema.Table{
		Name:        "carts",
		Columns:     CartsColumns,
		PrimaryKey:  []*schema.Column{CartsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "cost_cents", Type: field.TypeInt},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:        "items",
		Columns:     ItemsColumns,
		PrimaryKey:  []*schema.Column{ItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// LineItemsColumns holds the columns for the "line_items" table.
	LineItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "cart_line_items", Type: field.TypeUUID, Nullable: true},
		{Name: "line_item_item", Type: field.TypeUUID, Nullable: true},
	}
	// LineItemsTable holds the schema information for the "line_items" table.
	LineItemsTable = &schema.Table{
		Name:       "line_items",
		Columns:    LineItemsColumns,
		PrimaryKey: []*schema.Column{LineItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "line_items_carts_line_items",
				Columns: []*schema.Column{LineItemsColumns[2]},

				RefColumns: []*schema.Column{CartsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "line_items_items_item",
				Columns: []*schema.Column{LineItemsColumns[3]},

				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CartsTable,
		ItemsTable,
		LineItemsTable,
	}
)

func init() {
	LineItemsTable.ForeignKeys[0].RefTable = CartsTable
	LineItemsTable.ForeignKeys[1].RefTable = ItemsTable
}
