// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/awolk/lil-shop/backend/ent/runtime.go

const (
	Version = "v0.2.3"                                          // Version of ent codegen.
	Sum     = "h1:p943gSMnfEIWvfxALV84LY3QtaMjoo1m0hCXPATbY3k=" // Sum of ent codegen.
)
