// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/awolk/lil-shop/backend/ent/runtime.go

const (
	Version = "v0.2.5"                                          // Version of ent codegen.
	Sum     = "h1:VMw6rOhxKWeKpIMTzJCFswoECr4Wm8gvWIlqNz3L95c=" // Sum of ent codegen.
)
