// Code generated by entc, DO NOT EDIT.

package orderlineitem

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the orderlineitem type in the database.
	Label = "order_line_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldUnitCostCents holds the string denoting the unit_cost_cents field in the database.
	FieldUnitCostCents = "unit_cost_cents"

	// EdgeItem holds the string denoting the item edge name in mutations.
	EdgeItem = "item"
	// EdgeOrder holds the string denoting the order edge name in mutations.
	EdgeOrder = "order"
	// EdgeOriginalLineItem holds the string denoting the original_line_item edge name in mutations.
	EdgeOriginalLineItem = "original_line_item"

	// Table holds the table name of the orderlineitem in the database.
	Table = "order_line_items"
	// ItemTable is the table the holds the item relation/edge.
	ItemTable = "order_line_items"
	// ItemInverseTable is the table name for the Item entity.
	// It exists in this package in order to avoid circular dependency with the "item" package.
	ItemInverseTable = "items"
	// ItemColumn is the table column denoting the item relation/edge.
	ItemColumn = "order_line_item_item"
	// OrderTable is the table the holds the order relation/edge.
	OrderTable = "order_line_items"
	// OrderInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	OrderInverseTable = "orders"
	// OrderColumn is the table column denoting the order relation/edge.
	OrderColumn = "order_order_line_items"
	// OriginalLineItemTable is the table the holds the original_line_item relation/edge.
	OriginalLineItemTable = "order_line_items"
	// OriginalLineItemInverseTable is the table name for the LineItem entity.
	// It exists in this package in order to avoid circular dependency with the "lineitem" package.
	OriginalLineItemInverseTable = "line_items"
	// OriginalLineItemColumn is the table column denoting the original_line_item relation/edge.
	OriginalLineItemColumn = "order_line_item_original_line_item"
)

// Columns holds all SQL columns for orderlineitem fields.
var Columns = []string{
	FieldID,
	FieldQuantity,
	FieldUnitCostCents,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the OrderLineItem type.
var ForeignKeys = []string{
	"order_order_line_items",
	"order_line_item_item",
	"order_line_item_original_line_item",
}

var (
	// QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	QuantityValidator func(int) error
	// UnitCostCentsValidator is a validator for the "unit_cost_cents" field. It is called by the builders before save.
	UnitCostCentsValidator func(int) error
	// DefaultID holds the default value on creation for the id field.
	DefaultID func() uuid.UUID
)
